{{- range $product, $env := .Values }}
{{- range $envkey, $clusters := $env }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $product }}-{{ $envkey }}-product-apps-2
  namespace: argocd
spec:
  project: {{ $product }}-{{ $envkey }}
  source:
    helm:
      values: |
        product: {{ $product }}
        env: {{ $envkey }}
    repoURL: https://github.com/PullaPantangi/roboshop-k8s-26.git
    targetRevision: master
    path: applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
{{- end }}
{{- end }}

